# generate_registry.cmake — Auto-generates app_registry_init.cpp
#
# Scans source files for:
#   1. REGISTER_APP(Name, ...) macro usage
#   2. void _register_Name_app() function definitions
#
# Generates AppRegistry_InitAll() that calls all discovered registration functions.
#
# Usage in CMakeLists.txt:
#   include(cmake/generate_registry.cmake)
#   generate_app_registry("${CMAKE_BINARY_DIR}/app_registry_init.cpp" APP_SCAN_DIRS)

function(generate_app_registry OUTPUT_FILE SCAN_DIRS)
    set(APP_NAMES "")

    foreach(SCAN_DIR ${SCAN_DIRS})
        file(GLOB_RECURSE SCAN_SOURCES "${SCAN_DIR}/*.cpp")

        foreach(src ${SCAN_SOURCES})
            if(NOT EXISTS "${src}")
                continue()
            endif()
            file(READ "${src}" FILE_CONTENT)

            # Pattern 1: REGISTER_APP(Name, ...) macro
            string(REGEX MATCHALL "REGISTER_APP\\(([^,]+)," MATCHES "${FILE_CONTENT}")
            foreach(MATCH ${MATCHES})
                string(REGEX REPLACE "REGISTER_APP\\(([^,]+)," "\\1" APP_NAME "${MATCH}")
                string(STRIP "${APP_NAME}" APP_NAME)
                list(APPEND APP_NAMES "${APP_NAME}")
            endforeach()

            # Pattern 2: void _register_Name_app() function definition
            string(REGEX MATCHALL "void _register_([A-Za-z0-9_]+)_app\\(" MATCHES2 "${FILE_CONTENT}")
            foreach(MATCH ${MATCHES2})
                string(REGEX REPLACE "void _register_([A-Za-z0-9_]+)_app\\(" "\\1" APP_NAME "${MATCH}")
                string(STRIP "${APP_NAME}" APP_NAME)
                list(APPEND APP_NAMES "${APP_NAME}")
            endforeach()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES APP_NAMES)

    # Generate app_registry_init.cpp
    file(WRITE "${OUTPUT_FILE}" "// Auto-generated file - DO NOT EDIT\n")
    file(APPEND "${OUTPUT_FILE}" "// Generated by cmake/generate_registry.cmake\n\n")

    # Add extern declarations
    foreach(APP_NAME ${APP_NAMES})
        file(APPEND "${OUTPUT_FILE}" "extern void _register_${APP_NAME}_app();\n")
    endforeach()

    # Add initialization function
    file(APPEND "${OUTPUT_FILE}" "\nvoid AppRegistry_InitAll() {\n")
    foreach(APP_NAME ${APP_NAMES})
        file(APPEND "${OUTPUT_FILE}" "    _register_${APP_NAME}_app();\n")
    endforeach()
    file(APPEND "${OUTPUT_FILE}" "}\n")

    list(LENGTH APP_NAMES APP_COUNT)
    message(STATUS "Generated app_registry_init.cpp with ${APP_COUNT} apps: ${APP_NAMES}")
endfunction()
